# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit ghy5100.Rmd to modify this file

## ----setup, include = FALSE---------------------------------------------------
knitr::opts_chunk$set(
  dev = c("jpeg"),
  fig.align = "center"
)


## ----echo = FALSE-------------------------------------------------------------
plot(mtcars$mpg, mtcars$hp)

